// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xodoltxfdrtzsczyvidz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvZG9sdHhmZHJ0enNjenl2aWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODQwNzYsImV4cCI6MjA2OTU2MDA3Nn0.cjRBlXApvJVOWr7fOezKBZFt_FLgw3ewkAjW2fHcHhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});